### ISSUE TITLE
Fuseau horaire incorrect dans l'agenda ics

### ISSUE THREAD

**Issue by pierreboudes** [codegouvfr/codegouvfr-website#19]
L'agenda à l'URL `https://code.gouv.fr/mission-logiciels-libres.ics` annonce les évènements en donnant des horaires UTC au lieu de calculer le décalage pour le fuseau GMT+2.

Par exemple, l'évènement BlueHats https://code.gouv.fr/fr/bluehats/okdp/ a été annoncé comme ceci dans l'ics :
```
SUMMARY:Présentation de la plateforme OKDP
…
DTSTART:20240607T110000Z
```
Soit un début à 11:00 UTC le 7 juin alors que l'évènement débutait deux heures plus tôt. Pour un client réglé en GMT+2, heure de Paris, par exemple Thunderbird, cela conduit à afficher un début à 13h au lieu de 11h.

**Comment by hjonin** [comment]
Bonjour,

Merci de nous avoir signalé ce problème !

Ce devrait être corrigé sur le site : le `.ics` généré contient l'information de fuseau horaire (utc) qui devrait être interprétée dans le client de calendrier ; n'hésitez pas à nous signaler si cela ne fonctionne cependant toujours pas de votre côté !

**Comment by bzg** [comment]
Bonjour @pierreboudes - je ferme l'issue, n'hésite pas à la réouvrir si besoin.
